language: php

php:
  - 7.

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source
  - mysql -uroot < .travis/schema.sql

script:
  - mkdir -p build/logs
  - phpunit --configuration tests/phpunit.xml tests

after_script:
  - php vendor/bin/coveralls -v
