language: php

php:
  - 7.0

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source
  - mysql -uroot -e "create database bank"
  - mysql -uroot -e "use bank; CREATE TABLE `users` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(255) DEFAULT NULL,  PRIMARY KEY (`id`),  UNIQUE KEY `id` (`id`)) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8"

script:
  - mkdir -p build/logs
  - phpunit --configuration tests/phpunit.xml tests

after_script:
  - php vendor/bin/coveralls -v