language: php

php:
  - 7.0

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source
  - mysql -uroot -e "create database bank"
  - mysql -uroot -e "use bank; create table users (id int(11), name varchar(255))"

script:
  - mkdir -p build/logs
  - phpunit --configuration tests/phpunit.xml tests

after_script:
  - php vendor/bin/coveralls -v